### ISSUE TITLE
Dynamically create FTP connection config

### ISSUE THREAD

**Issue by njbarrett** [GrahamCampbell/Laravel-Manager#9]
Hi, just wondering if you could assist with how to create an FTP connection dynamically, e.g FTP details are stored on a Model and I want to create a new connection at runtime rather than stored in the config/flysystem.php

The facade doesn't implement the createConnection method so I am having trouble figuring it out.

Thanks

**Comment by GrahamCampbell** [comment]
You can absolutely have dynamic connections. You'd just not use this manager class, and go direct to your factory class.

Here's a real world example:

https://github.com/GrahamCampbell/Laravel-GitHub/blob/master/src/GitHubManager.php
https://github.com/GrahamCampbell/Laravel-GitHub/blob/master/src/GitHubFactory.php

You'd resolve the factory class out of ioc to dynamically make instances, and use the manager class to resolve instances from config.

---

> The facade doesn't implement the createConnection method so I am having trouble figuring it out.

Yeh, this is because this is a `protected` method.

You do make me wonder if things would be easier to use if I made this method `public`, however, doing that would require a new major version, and would require every dependent of this package to change their code in order to upgrade, so I'm very hesitant to change the visibility. I guess I could also add a new public method to the abstract manager that calls this protected one to get around BC problems, provided I'm able to choose a non-obscure method name that I am also sure nobody extending the class has used.

**Comment by njbarrett** [comment]
Thanks heaps for the response.
It seems the `FlysystemFactory` class has the method signature for make as
`public function make(array $config, FlysystemManager $manager)`
How would I pass through the correct `$manager` instance to the make function?

**Comment by njbarrett** [comment]
Nevermind, got it.

```
$contents = Flysystem::getFactory()->make($config, app('flysystem'));

I dont think changing the `createConnection` visibility is necessary but a note in the docs would be helpful I am sure.
```

**Comment by GrahamCampbell** [comment]
👍
